version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL}
      - REACT_APP_HOURS_CLOSE_TICKETS_AUTO=${HOURS_CLOSE_TICKETS}
    depends_on:
      - backend
    networks:
      - whatic_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - PROXY_PORT=${PROXY_PORT}
      - PORT=${PORT}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - REDIS_URI=redis://:${REDIS_PASS}@redis:6379
      - REDIS_OPT_LIMITER_MAX=${REDIS_OPT_LIMITER_MAX}
      - REDIS_OPT_LIMITER_DURATION=${REDIS_OPT_LIMITER_DURATION}
      - USER_LIMIT=${USER_LIMIT}
      - CONNECTIONS_LIMIT=${CONNECTIONS_LIMIT}
      - CLOSED_SEND_BY_ME=${CLOSED_SEND_BY_ME}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
    depends_on:
      - postgres
      - redis
    networks:
      - whatic_network

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - whatic_network

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - whatic_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certificates:/etc/nginx/certificates
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - whatic_network

networks:
  whatic_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
