services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=senha
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  postgres:
